apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Deployment
    metadata:
      labels:
        app: ${APP}
      name: ${APP}
    spec:
      replicas: 1
      selector:
        app: ${APP}
        deploymentconfig: ${APP}
      strategy:
        type: Rolling
        rollingParams:
          intervalSeconds: 1
          maxUnavailable: 25%
          maxSurge: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
      template:
        metadata:
#          annotations:
#            splunk.com/nonprod-index: 1234_ABCD
#            splunk.com/sourcetype: abc-service-dev
          labels:
            app: ${APP}
            deploymentconfig: ${APP}
        spec:
          containers:
              image: ${REG}/${AIT}/${IMG}:${TAG}
              imagePullPolicy: Always
              name: ${APP}
              ports:
                - containerPort: 8081
                  protocol: TCP
              env:
                - name: GC_MAX_METASPACE_SIZE
                  value: '256'
                - name: JAVA_OPTIONS
                  value: '-Duser.timezone=UTC'
          resources : {}
          terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
parameters:
  - description: App Name
    displayName: App Name
    name: APP
    required: true
  - name: REG
    description:  Registry
    displayName: Registry
    required: true
  - name: TAG
    description: Release Tag
    displayName: Tag
    required: true
  - name: IMG
    description: Image Name
    displayName: IMG
    required: true
  - name: AIT
    description: AIT Name
    displayName: AIT
    required: true